http.cors.allow-origin: "/.*/"
http.cors.enabled: true
cluster.name: elasticsearch
node.name: "bvc.elasticsearch.brocade.com"
node.max_local_storage_nodes: 1
index.mapper.dynamic: true
action.auto_create_index: true
action.disable_delete_all_indices: true
path.conf: /bvc/configs
path.data: /bvc/elasticsearch/data
path.work: /bvc/elasticsearch/work
path.logs: /bvc/elasticsearch/logs
bootstrap.mlockall: true
gateway.expected_nodes: 1
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.multicast.enabled: false


